# path to a directory with all packages
storage: /data
users:
  humanstage:
      # crypto.createHash('sha1').update(pass).digest('hex')
      password: 61cae9c2ff531fc11f46e110ce12c421c77a54b4

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@humanstage/*':
    # scoped packages
    access: $all
    publish: $authenticated

  '*':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $all

    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: sinopia.log, level: info}

listen:
  - 0.0.0.0:4873
